name: Always Succeeds
on: [push, workflow_dispatch] # Trigger on push or manually
jobs:
  succeed:
    runs-on: ubuntu-latest
    steps:
      - name: Run a successful command
        run: echo "This workflow succeeded!"